set shell := ["nu", "-c"]
python := ".venv/Scripts/python.exe"

server:
    @ {{python}} src/main.py server -host 0.0.0.0 -port 4050

test:
    @ {{python}} -m pytest

main *t:
    @ {{python}} src/main.py {{t}}

migrate t:
    @ dbmate -d "migration/revision" -s "migration" -u "postgres://postgres:1234@localhost:5432/achievements?sslmode=disable" {{t}}
